language: python

python:
  - 3.6

# install dependencies
install:
  - pip install -r requirements/dev.txt
  - npm install cypress --save-dev

# this needs to be running before the tests are run

script:
  - "echo 'Initiating flask app'"
  - run directory_location.sh
  - "export FLASK_APP=app.py"
  - "flask run"
  - "echo 'Running Integration tests'"
  - "cypress run --spec /cypress/integration/index_spec.js"
  - sleep 3 # give time to completely finish off

deploy:
  skip_cleanup: true