language: python
python:
  - 3.6

cache:
  directories:
    - ~/.npm
    - node_modules

before_install:
  - nvm install 6.11
  - nvm use 6.11

# install dependencies
install:
  - npm install
  - pip install -r requirements/dev.txt

# this needs to be running before the tests are run
pre_script:
  - echo 'Initiating flask app'
  - export FLASK_APP=webcam-example/app.py


script:
#  - $(npm bin)/cypress run --spec cypress/integration/index_spec.js
  - flask run & sleep 5 & $(npm bin)/cypress run

deploy:
  skip_cleanup: true