language: python

python:
  - 3.6

# install dependencies
install:
  - pip install -r requirements/dev.txt
  - nvm install 0.10
  - npm install cypress --save-dev

# this needs to be running before the tests are run
pre_script:
  - "echo 'Initiating flask app'"
  - directory_location.sh
  - "export FLASK_APP=app.py"
  - sleep 5

script:
  - "flask run"
  - "echo 'Running Integration tests'"
  - "cypress run --spec /cypress/integration/index_spec.js"
  - sleep 5 # give time to completely finish off

deploy:
  skip_cleanup: true